<a href="https://colab.research.google.com/github/Soham-123-code/Projects/blob/main/Python_syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Hello World")

Hello World


In [ ]:
def HelloWorldXY(x,y):
  if (x < 10):
    print("Hello World, x was < 10")
  elif (x < 20):
    print ("Hello World, x < 20")
  else:
    print ("Hello World, x was >= 20")
  return x+y
for i in range(8,25,5):
    print("--- Now running with i: {}".format(i))
    r=HelloWorldXY(i,i)
    print("Result from HelloWorld: {}".format(i,r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 8
--- Now running with i: 13
Hello World, x < 20
Result from HelloWorld: 13
--- Now running with i: 18
Hello World, x < 20
Result from HelloWorld: 18
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 23


In [ ]:
print (HelloWorldXY(1,2))

Hello World, x was < 10
3


In [ ]:
print ("Iterate over the items .'range(2)' is like the list [0,1].")
for i in range(2):
  print(i)

print("Iterate over an actual list") 
for i in [0,1]:
  print(i)

print("While works")
i=0
while i < 2:
  print(i)
  i += 1

Iterate over the items .'range(2)' is like the list [0,1].
0
1
Iterate over an actual list
0
1
While works
0
1


In [ ]:
print("Python supports standard key words like continue and break")
while True:
  print("Entered while")
  break

Python supports standard key words like continue and break
Entered while


In [10]:
import numpy as np #make numpy avaliable using np
# create an numpy array and append an element 
a=np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index ")
e=0
for i,e in enumerate(a):
    print("Index: {}, was: {}".format(i.e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index 


AttributeError: ignored

In [9]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3,3)
print(c) 


Use numpy to create a [3,3] dimension array with random number
[[0.30763234 0.08549165 0.29623561]
 [0.78830476 0.71665347 0.66811349]
 [0.48036424 0.60309396 0.88417583]]


In [11]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {]".format(b.shape))
print("Shape of c: {}".format(c.shape))


You can print the dimensions of arrays
Shape of a: (3,)


ValueError: ignored

In [12]:
print("Install numpy")
!pip install numpy

Install numpy


In [14]:
!pwd
!ls -l

/content
total 4
drwxr-xr-x 1 root root 4096 Mar 23 14:22 sample_data


In [15]:
!pwd
!cd /
!ls -l

/content
total 4
drwxr-xr-x 1 root root 4096 Mar 23 14:22 sample_data
